name: integration-demo

on:
  push:
    branches:
      - master

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Run some scripts
        run: echo "hello world"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependency
        run: yarn

      - name: Run test
        run: yarn run test
